mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy("polls:index")), name='home'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
#     url(r'^d3/$', views.d3_voteData, name='d3'),
    url(r'^search/$', views.autocomplete_companyData, name='autocomplete_companyData'),
    url(r'^question$', views.QuestionCreate.as_view(), name='question'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.db.models.signals import pre_save
from polls.validators import validate_badwords


class Company(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default=None, null=True)
    B2B = "B2B"
    B2A = "B2A"
    B2C = "B2C"

    BUSINESS_CHOICES = ((B2B, "B2B"), (B2A, "B2A"), (B2C, "B2C"))
    business = models.CharField(max_length=3,
                                choices=BUSINESS_CHOICES,
                                default=B2A)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


def check_user_words(sender, instance, **kwargs):
    for field in instance._meta.get_fields():
        if (isinstance(field, models.CharField)):
                validate_badwords(getattr(instance, field.attname))


class Question(models.Model):
    question_text = models.CharField(max_length=200,
                                     validators=[validate_badwords])
    pub_date = models.DateTimeField('date published')
    company = models.ForeignKey(Company,
                                on_delete=models.CASCADE,
                                null=True,
                                default=None)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200,
                                   validators=[validate_badwords])
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


pre_save.connect(check_user_words, sender=Question)
pre_save.connect(check_user_words, sender=Choice)

mysite/polls/forms.py
from django import forms
from polls.models import Question, Choice
from django.forms.models import inlineformset_factory


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['question_text', 'company']
        labels = {
            'question_text': ('Question'),
            'company': ('Company')
        }
        widgets = {
            'question_text': forms.TextInput(attrs={'placeholder': 'Enter Question'}),
            'company': forms.TextInput(attrs={'id': 'companiesList'}),
        }


ChoiceInlineFormSet = inlineformset_factory(Question,
                                            Choice,
                                            fields=['question', 'choice_text'],
                                            exclude=[], can_delete=False)

mysite/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question, Company
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from polls.forms import QuestionForm, ChoiceInlineFormSet
import json


# I DON'T KNOW HOW TO USE THIS IN D3 YET.
# data to extract choices and votes into a dict list
# [{'choice_text': u'hello', 'votes': 5}, {'choice_text': u'there', 'votes': 1}, {'choice_text': u'u', 'votes': 1}]
def d3_voteData(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices_votes = question.choice_set.all().values('choice_text',
                                                     'votes')
    choices_list = list(choices_votes) # convert the QuerySet to a list object
    return JsonResponse(choices_list, safe=False)


def autocomplete_companyData(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        companies = Company.objects.filter(name__startswith=q)
        results = []
        for company in companies:
            company_json = {}
            company_json['id'] = company.pk
            company_json['label'] = company.name
            company_json['value'] = company.name
            results.append(company_json)
        data = json.dumps(results)
    else:
        data = 'why im i failing??'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


class QuestionCreate(CreateView):
    template_name = 'polls/question_form.html'
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('polls:index')

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests. Instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form = QuestionForm()
        choice_form = ChoiceInlineFormSet()
        return self.render_to_response(
            self.get_context_data(form=form, choice_form=choice_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests. Instantiates a form instance and its inline
        formsets with the passed POST inputs, then checks for
        validity.
        """
        self.object = None
        form = QuestionForm(self.request.POST)
        choice_form = ChoiceInlineFormSet(self.request.POST)
        if (form.is_valid() and choice_form.is_valid()):
            return self.form_valid(form, choice_form)
        else:
            return self.form_invalid(form, choice_form)

    def form_valid(self, form, choice_form):
        """
        If form is valid, creates a Question instance along with
        associated Choices and redirects to index page.
        """
        self.object = form.save(commit=False)
        self.object.pub_date = timezone.now()
        self.object.save()
        choice_form.instance = self.object
        choice_form.save()
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form, choice_form):
        """
        If form is invalid, re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form, choice_form=choice_form))


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results',
                                            args=(question.id,)))

mysite/polls/templates/polls/choices.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

{% block body %}
<div class="container-fluid">
	<form method= "post">
		<label>Please enter your choices: </label>
		{% csrf_token%}
		{{ form.as_p}}
		{{ formset.management_form }}
			<table>
        		<h2>Choices</h2>
        		{% if formset.non_form_errors %}
           			<p>{{ formset.non_form_errors }}</p>
       			{% endif %}
       			{% for form in formset %}
       				{{ form }}
      			{% endfor %}
    		</table>
		<button type="submit" class="btn btn-primary">Add Choices</button>
	</form>
	{% if error_message %}
	<h2> {{ error_message }} </h2>	  
	{% endif %}
	<br>
</div>
{%endblock%}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

mysite/polls/templates/polls/detail.html
{% load static %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>


<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="{% static 'polls/js/votesBarGraph.js' %}"></script>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<!DOCTYPE html>
<html>
<head>
	<title>Polls Webpage</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<div class = "container-fluid">
		<h2>Welcome to Katie's Polls Webpage</h2>

		{% if latest_question_list %}
		    <ul>
		    {% for question in latest_question_list %}
		    	<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
		<br>
		<!-- <a href="{% url 'polls:question' %}">Add a New Question</a> -->	 
		<a class="btn btn-primary" href="{% url 'polls:question' %}" role="button">Add a New Question</a>
	</div>
</body>
</html>

mysite/polls/templates/polls/question_form.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


{% load static %}
{% block body %}
<div class= "container-fluid">
	<h1>Polls</h1>
	<form method= "post">	
		<div class="form-group">
		    <label for="companiesList">Please enter a Company and Question: </label>
		    	{% csrf_token%}
		    	{{ form.as_p}}
				 <table>
                	<label for="enteringchoices">Enter Choices: </label>
               		 <br>
	                {{ choice_form.management_form }}
	                {{ choice_form.non_form_errors }}
	                {% for form in choice_form %}
                    	{{ form }}
                	{% endfor %}
            	</table>
		</div>
    <button type="submit" class="btn btn-primary" id="id_company">Add your choices</button>
    
	</form>
	{% if error_message %}
	<h2> {{ error_message }} </h2>	  
	{% endif %}

<script src="{% static 'polls/js/ajax_autocomplete.js' %}"></script>

</div>
{%endblock%}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<div>
	<script src="https://d3js.org/d3.v3.min.js"></script>
	<script> var source ="{% url 'polls:d3_voteData' question.id %}"</script>  
	<script src="{% static 'polls/js/votesBarGraph.js' %}" ></script>	
</div>